### ISSUE TITLE
Develop is behind master

### ISSUE THREAD

**Issue by brandonio21** [prkumar/uplink#1]
The develop branch is behind the master branch. I'm assuming that "master" should be more stable than develop. Should develop be updated and all PRs be merged into develop rather than master?

**Comment by prkumar** [comment]
@brandonio21 Darn, seems like I mistakenly merged my feature branch into `master` instead of `develop` earlier this night.

You're right: `master` should be more stable than `develop`. And, all PRs should be merged into `develop` rather than `master`. 

To fix this, I'm going to do a fast-forward merge of `master` into `develop`.

**Comment by prkumar** [comment]
Fixed with a fast-forward merge of `master` into `develop`.

**Comment by prkumar** [comment]
# UPDATE!

I've renamed the "more stable" branch to ``stable``, and the work-in-progress branch is now ``master``. In other words, the old ``master`` is now ``stable``, and the old ``develop`` is now ``master``.

This change was mainly made for two reasons:

* HEAD should be at the latest development code
* Want to avoid the logistical hassle of maintaining a default branch not named ``master``.

The contribution guide and other material referencing the old branching model have been updated appropriately.

FYI: @brandonio21

**Comment by brandonio21** [comment]
@prkumar Great! IMO, this is the superior branching pattern
